# This workflow will install Python dependencies, run tests and test coverage
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches: 
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m nltk.downloader -d /usr/share/nltk_data all
        python -m textblob.download_corpora
    - name: Test with pytest
      run: |
        pytest tests/
    - name: Test coverage
      run: |
        pytest tests/ --cov --cov-fail-under=60         
